# Generated by Django 4.0.7 on 2022-12-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
    ]
